version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
